[package]
name = "seven-mail"
version = "0.4.0"
description = "Seven Mail desktop client"
authors = ["gabriell211"]
edition = "2021"

[lib]
name = "seven_mail_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-autostart = "2"
tauri-plugin-notification = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
dirs = "6"
keyring = "3"
lettre = { version = "0.11.23", default-features = false, features = ["builder", "smtp-transport", "rustls", "ring", "webpki-roots"] }
async-imap = "0.11.3"
async-native-tls = "0.6.0"
async-std = "1.13.2"
futures = "0.3.31"
mail-parser = "0.11.9"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
base64 = "0.22"
zip = { version = "4.6", default-features = false, features = ["deflate"] }
aes-gcm = "0.10"
rand = "0.8"
reqwest = { version = "0.13", features = ["blocking"] }
regex = "1"
ldap3 = "0.12.1"
